### PR TITLE
Loop accumulate not in the name of the file, but in the tag of hd5f file

### PR DESCRIPTION
**Pull request by pittlerf**

### CODE REVIEW

**Comment by kostrzewa** [comment]
What about the other changes such as separate files for the derivatives, if text files are produced?

**Comment by kostrzewa** [comment]
Just wondering if these were the only changes that you made recently

**Comment by pittlerf** [comment]
> Just wondering if these were the only changes that you made recently

Yes, with this commit I made actually the loop filterings.

**Comment by kostrzewa** [comment]
From the text file output, how do I tell if the loops are accumulated or not?

**Comment by kostrzewa** [comment]
we should probably also make the text file output an actual feature. That is, instead of depending on the verbosity level, there should be an actual flag to trigger it, I guess...

**Pull request merged**
